# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_dlmb_bram_if_cntlr_0/System_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'System_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_dlmb_bram_if_cntlr_0/System_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_dlmb_bram_if_cntlr_0/System_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'System_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_dlmb_bram_if_cntlr_0/System_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
