# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/System_smartconnect_0_1.xci
# IP: The module: 'System_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/bd_48c1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_0/bd_48c1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_2/bd_48c1_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_3/bd_48c1_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_4/bd_48c1_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_5/bd_48c1_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_6/bd_48c1_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_7/bd_48c1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_8/bd_48c1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_9/bd_48c1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_10/bd_48c1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_11/bd_48c1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_12/bd_48c1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_13/bd_48c1_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_14/bd_48c1_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_15/bd_48c1_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_16/bd_48c1_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_17/bd_48c1_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_18/bd_48c1_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_19/bd_48c1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_20/bd_48c1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_21/bd_48c1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_22/bd_48c1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_23/bd_48c1_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_24/bd_48c1_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_25/bd_48c1_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_26/bd_48c1_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_27/bd_48c1_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_28/bd_48c1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_2/bd_48c1_arsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_3/bd_48c1_rsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_4/bd_48c1_awsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_5/bd_48c1_wsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_6/bd_48c1_bsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_10/bd_48c1_s00a2s_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_11/bd_48c1_sarn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_12/bd_48c1_srn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_16/bd_48c1_s01a2s_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_17/bd_48c1_sarn_1_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_18/bd_48c1_srn_1_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_19/bd_48c1_sawn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_20/bd_48c1_swn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_21/bd_48c1_sbn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_22/bd_48c1_m00s2a_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_23/bd_48c1_m00arn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_24/bd_48c1_m00rn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_25/bd_48c1_m00awn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_26/bd_48c1_m00wn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_27/bd_48c1_m00bn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/System_smartconnect_0_1.xci
# IP: The module: 'System_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/bd_48c1.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_0/bd_48c1_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_2/bd_48c1_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_3/bd_48c1_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_4/bd_48c1_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_5/bd_48c1_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_6/bd_48c1_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_7/bd_48c1_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_8/bd_48c1_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_9/bd_48c1_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_10/bd_48c1_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_11/bd_48c1_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_12/bd_48c1_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_13/bd_48c1_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_14/bd_48c1_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_15/bd_48c1_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_16/bd_48c1_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_17/bd_48c1_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_18/bd_48c1_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_19/bd_48c1_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_20/bd_48c1_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_21/bd_48c1_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_22/bd_48c1_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_23/bd_48c1_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_24/bd_48c1_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_25/bd_48c1_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_26/bd_48c1_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_27/bd_48c1_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_28/bd_48c1_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_1/bd_48c1_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_2/bd_48c1_arsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_3/bd_48c1_rsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_4/bd_48c1_awsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_5/bd_48c1_wsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_6/bd_48c1_bsw_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_10/bd_48c1_s00a2s_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_11/bd_48c1_sarn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_12/bd_48c1_srn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_16/bd_48c1_s01a2s_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_17/bd_48c1_sarn_1_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_18/bd_48c1_srn_1_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_19/bd_48c1_sawn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_20/bd_48c1_swn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_21/bd_48c1_sbn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_22/bd_48c1_m00s2a_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_23/bd_48c1_m00arn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_24/bd_48c1_m00rn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_25/bd_48c1_m00awn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_26/bd_48c1_m00wn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/bd_0/ip/ip_27/bd_48c1_m00bn_0_ooc.xdc

# XDC: c:/Users/Michael/Lab_hardware_handout/Lab_hardware_handout.srcs/sources_1/bd/System/ip/System_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
